name: Deploy to github pages
on: [push]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: "Set remote and user"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name github-actions-bot
          git config user.email support+actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Deploy
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
